name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key328dfdfdgsgÑ
      - run: curl https://api.ipify.org
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.test }}" > "$HOME/.ssh/test"
      - run: chmod 0600 "$HOME/.ssh/test"
      # Deploy
      - run: rsync -e "ssh -p 22 -vvv -i $HOME/.ssh/test -o StrictHostKeyChecking=no" --archive --compress --delete . j01391837@maphr.ru:/home/users/j/j01391837/domains/maphr.ru
      - name: Copy .env.example to .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
